version: '2'
volumes:
  datagraft-data:
    driver: local
  datagraft-uploads:
    driver: local
services:
  database:
    ports:
      - "5433:5432"
    container_name: datagraft-db
    image: postgres:9.5
    volumes:
      - datagraft-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: datagraft-dev
  datagraft-portal:
    container_name: datagraft-portal
    image: datagraft/datagraft-portal
    ports:
      - "3003:3000"
    links:
      - database:database-host
    command: bash startup.sh
    volumes:
      - datagraft-uploads:/usr/src/app/tmp/uploads/store
    environment:
      DATABASE_URL: postgresql://postgres:password@database-host
      DATABASE_HOST: localhost
      DATABASE_PASSWORD: password
      RAILS_ENV: development
      SECRET_KEY_BASE: secretkeybase
      GRAFTERIZER_PUBLIC_PATH: http://localhost:9000
      GRAFTWERK_URI: http://localhost:8087
      DATAGRAFT_DEPLOY_HOST: localhost
      DATAGRAFT_DEPLOY_PORT: 3003 
  grafterizer:
    container_name: grafterizer
    image: datagraft/grafterizer2
    ports:
      - "9000:80"
    links:
      - graftwerk
      - grafterizer-dispatch-service
      - vocabulary-manager
      - graftwerk-cache
      - jarfter
      - arango-generator
    restart: always
  grafterizer-dispatch-service:
    container_name: grafterizer-dispatch-service
    image: datagraft/grafterizer-dispatch-service
    links:
      - graftwerk
      - graftwerk-cache
      - datagraft-portal
    ports:
      - "8082:8082"
    environment:
      COOKIE_STORE_SECRET: cookiestoresecret
      OAUTH2_CLIENT_ID: grafterizerUID
      OAUTH2_CLIENT_SECRET: grafterizerSecret
      GRAFTWERK_URI: http://graftwerk:8080
      GRAFTWERK_CACHE_URI: http://graftwerk-cache:8082
      DATAGRAFT_URI: http://datagraft-portal:3000
      # Public URI of grafterizer-web-dev.
      # This URI MUST be accessible by the end-user.
      CORS_ORIGIN: http://localhost:9000
      # Public URI of the backend server.
      # This URI MUST be accessible by the end-user.
      PUBLIC_CALLBACK_SERVER: http://localhost:8082
      # same as DATAGRAFT_URI by default
      PUBLIC_OAUTH2_SITE: http://localhost:3003
    restart: always
  graftwerk-cache:
    container_name: graftwerk-cache
    image: datagraft/graftwerk-cache
    ports:
      - "8083:8082"
    links:
      - graftwerk
    environment:
      GRAFTWERK: graftwerk
      GRAFTWERK_PORT: 8080
    restart: always
  graftwerk:
    container_name: graftwerk
    image: datagraft/graftwerk
    ports:
      - "8087:8080"
    environment:
      PORT: 8080
    restart: always
  vocabulary-manager:
    container_name: grafterizer-vocabulary
    image: dapaas/grafterizer-vocabulary
    restart: always
    ports:
      - "8088:8080"
  jarfter:
    container_name: jarfter
    image: datagraft/jarfter
    restart: always
    ports:
      - "8081:8080"
  arango-generator:
    container_name: arango-generator
    environment:
      HTTP_PORT: 3030
      RESULT_STORAGE_LOCATION: ./results/
      INPUT_STORAGE_LOCATION: ./uploads/
    ports:
      - "3030:3030"
    image: datagraft/arango-generator
    restart: always